# Generated by Django 4.2 on 2023-04-15 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_evento_criador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='data_terminio',
            new_name='data_termino',
        ),
    ]
